name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ConsoleApp1,ConsoleApp2]
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    #- name: Restore dependencies
    #  run: dotnet restore ./**/*.csproj
    - name: Build
      run: dotnet build AzureContainers.sln
      continue-on-error: true
    - name: Test
      run: dotnet test --no-build --verbosity normal AzureContainers.sln
    - name: Upload ${{ matrix.project }}
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name:  ${{ matrix.project }}
        # A file, directory or wildcard pattern that describes what to upload
        path:  ${{ matrix.project }}/bin/release/net6.0
        retention-days: 1
        
  containerise:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
            # Path to the Dockerfile
            file: ./${{ matrix.project }}
  
