name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    #- name: Restore dependencies
    #  run: dotnet restore ./**/*.csproj
    - name: Build
      run: dotnet build AzureContainers.sln
      continue-on-error: true
    - name: Test
      run: dotnet test --no-build --verbosity normal AzureContainers.sln

      
  
