name: Terraform 
on:
  repository_dispatch 

jobs:
  environment: dev
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:

     - name: Checkout
       uses: actions/checkout@v2
     - name: Terraform Init
       uses: hashicorp/terraform-github-actions/init@v0.4.0
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

     - name: Terraform Validate
       uses: hashicorp/terraform-github-actions/validate@v0.3.7

     - name: Terraform Apply
       uses: hashicorp/terraform-github-actions/apply@v0.4.0
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      
      

